
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
